"""initial schema

Revision ID: 56a3222b520e
Revises: 
Create Date: 2026-09-08 10:23:35.081933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '56a3222b520e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project'))
    )
    op.create_table('release_policy',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('thresholds', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('max_safety_violations', sa.Integer(), nullable=False),
    sa.CheckConstraint('max_safety_violations >= 0', name=op.f('ck_release_policy_max_safety_violations_nonneg')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_release_policy'))
    )
    op.create_table('dataset',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('version >= 1', name=op.f('ck_dataset_version_positive')),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_dataset_project_id_project'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dataset')),
    sa.UniqueConstraint('project_id', 'name', 'version', name=op.f('uq_dataset_project_id_name_version'))
    )
    op.create_index(op.f('ix_dataset_project_id'), 'dataset', ['project_id'], unique=False)
    op.create_table('system_version',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.Enum('openai', 'anthropic', 'ollama', name='provider_name', native_enum=False), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('prompt_template', sa.Text(), nullable=False),
    sa.Column('parameters', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('rag_config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('tool_policy', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_system_version_project_id_project'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_version')),
    sa.UniqueConstraint('project_id', 'name', 'version', name=op.f('uq_system_version_project_id_name_version'))
    )
    op.create_index(op.f('ix_system_version_project_id'), 'system_version', ['project_id'], unique=False)
    op.create_table('dataset_case',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('dataset_id', sa.String(length=32), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('input', sa.Text(), nullable=False),
    sa.Column('expected_output', sa.Text(), nullable=True),
    sa.Column('origin', sa.Enum('authored', 'promoted_trace', name='case_origin', native_enum=False), nullable=False),
    sa.Column('source_trace_id', sa.String(length=32), nullable=True),
    sa.CheckConstraint("(origin = 'promoted_trace') = (source_trace_id IS NOT NULL)", name=op.f('ck_dataset_case_trace_id_iff_promoted')),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], name=op.f('fk_dataset_case_dataset_id_dataset'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dataset_case')),
    sa.UniqueConstraint('dataset_id', 'position', name=op.f('uq_dataset_case_dataset_id_position'))
    )
    op.create_index(op.f('ix_dataset_case_dataset_id'), 'dataset_case', ['dataset_id'], unique=False)
    op.create_table('experiment',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('dataset_id', sa.String(length=32), nullable=False),
    sa.Column('baseline_version_id', sa.String(length=32), nullable=False),
    sa.Column('candidate_version_id', sa.String(length=32), nullable=False),
    sa.Column('release_policy_id', sa.String(length=32), nullable=True),
    sa.Column('repeats', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('baseline_version_id <> candidate_version_id', name=op.f('ck_experiment_baseline_ne_candidate')),
    sa.CheckConstraint('repeats >= 1', name=op.f('ck_experiment_repeats_positive')),
    sa.ForeignKeyConstraint(['baseline_version_id'], ['system_version.id'], name=op.f('fk_experiment_baseline_version_id_system_version'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['candidate_version_id'], ['system_version.id'], name=op.f('fk_experiment_candidate_version_id_system_version'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], name=op.f('fk_experiment_dataset_id_dataset'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_experiment_project_id_project'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['release_policy_id'], ['release_policy.id'], name=op.f('fk_experiment_release_policy_id_release_policy'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiment'))
    )
    op.create_index(op.f('ix_experiment_baseline_version_id'), 'experiment', ['baseline_version_id'], unique=False)
    op.create_index(op.f('ix_experiment_candidate_version_id'), 'experiment', ['candidate_version_id'], unique=False)
    op.create_index(op.f('ix_experiment_dataset_id'), 'experiment', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_experiment_project_id'), 'experiment', ['project_id'], unique=False)
    op.create_index(op.f('ix_experiment_release_policy_id'), 'experiment', ['release_policy_id'], unique=False)
    op.create_table('evaluation_result',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('experiment_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiment.id'], name=op.f('fk_evaluation_result_experiment_id_experiment'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluation_result'))
    )
    op.create_index(op.f('ix_evaluation_result_experiment_id'), 'evaluation_result', ['experiment_id'], unique=False)
    op.create_table('evaluation_run',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('experiment_id', sa.String(length=32), nullable=False),
    sa.Column('system_version_id', sa.String(length=32), nullable=False),
    sa.Column('case_id', sa.String(length=32), nullable=False),
    sa.Column('repeat_index', sa.Integer(), nullable=False),
    sa.Column('output', sa.Text(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('prompt_tokens >= 0 AND completion_tokens >= 0 AND cost_usd >= 0 AND latency_ms >= 0', name=op.f('ck_evaluation_run_usage_nonneg')),
    sa.CheckConstraint('repeat_index >= 0', name=op.f('ck_evaluation_run_repeat_index_nonneg')),
    sa.ForeignKeyConstraint(['case_id'], ['dataset_case.id'], name=op.f('fk_evaluation_run_case_id_dataset_case'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiment.id'], name=op.f('fk_evaluation_run_experiment_id_experiment'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['system_version_id'], ['system_version.id'], name=op.f('fk_evaluation_run_system_version_id_system_version'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluation_run')),
    sa.UniqueConstraint('experiment_id', 'system_version_id', 'case_id', 'repeat_index', name=op.f('uq_evaluation_run_experiment_id_system_version_id_case_id_repeat_index'))
    )
    op.create_index(op.f('ix_evaluation_run_case_id'), 'evaluation_run', ['case_id'], unique=False)
    op.create_index(op.f('ix_evaluation_run_experiment_id'), 'evaluation_run', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_evaluation_run_system_version_id'), 'evaluation_run', ['system_version_id'], unique=False)
    op.create_table('case_result',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['evaluation_run.id'], name=op.f('fk_case_result_run_id_evaluation_run'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_result')),
    sa.UniqueConstraint('run_id', name=op.f('uq_case_result_run_id'))
    )
    op.create_index(op.f('ix_case_result_run_id'), 'case_result', ['run_id'], unique=False)
    op.create_table('metric_comparison',
    sa.Column('evaluation_result_id', sa.String(length=32), nullable=False),
    sa.Column('metric', sa.String(length=200), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('baseline_value', sa.Float(), nullable=False),
    sa.Column('candidate_value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_result_id'], ['evaluation_result.id'], name=op.f('fk_metric_comparison_evaluation_result_id_evaluation_result'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('evaluation_result_id', 'metric', name=op.f('pk_metric_comparison')),
    sa.UniqueConstraint('evaluation_result_id', 'position', name=op.f('uq_metric_comparison_evaluation_result_id_position'))
    )
    op.create_index(op.f('ix_metric_comparison_evaluation_result_id'), 'metric_comparison', ['evaluation_result_id'], unique=False)
    op.create_table('evaluator_score',
    sa.Column('case_result_id', sa.String(length=32), nullable=False),
    sa.Column('evaluator', sa.String(length=200), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('family', sa.Enum('deterministic', 'statistical', 'llm_judge', name='evaluator_family', native_enum=False), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.CheckConstraint('score >= 0.0 AND score <= 1.0', name=op.f('ck_evaluator_score_score_unit_interval')),
    sa.ForeignKeyConstraint(['case_result_id'], ['case_result.id'], name=op.f('fk_evaluator_score_case_result_id_case_result'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('case_result_id', 'evaluator', name=op.f('pk_evaluator_score')),
    sa.UniqueConstraint('case_result_id', 'position', name=op.f('uq_evaluator_score_case_result_id_position'))
    )
    op.create_index(op.f('ix_evaluator_score_case_result_id'), 'evaluator_score', ['case_result_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evaluator_score_case_result_id'), table_name='evaluator_score')
    op.drop_table('evaluator_score')
    op.drop_index(op.f('ix_metric_comparison_evaluation_result_id'), table_name='metric_comparison')
    op.drop_table('metric_comparison')
    op.drop_index(op.f('ix_case_result_run_id'), table_name='case_result')
    op.drop_table('case_result')
    op.drop_index(op.f('ix_evaluation_run_system_version_id'), table_name='evaluation_run')
    op.drop_index(op.f('ix_evaluation_run_experiment_id'), table_name='evaluation_run')
    op.drop_index(op.f('ix_evaluation_run_case_id'), table_name='evaluation_run')
    op.drop_table('evaluation_run')
    op.drop_index(op.f('ix_evaluation_result_experiment_id'), table_name='evaluation_result')
    op.drop_table('evaluation_result')
    op.drop_index(op.f('ix_experiment_release_policy_id'), table_name='experiment')
    op.drop_index(op.f('ix_experiment_project_id'), table_name='experiment')
    op.drop_index(op.f('ix_experiment_dataset_id'), table_name='experiment')
    op.drop_index(op.f('ix_experiment_candidate_version_id'), table_name='experiment')
    op.drop_index(op.f('ix_experiment_baseline_version_id'), table_name='experiment')
    op.drop_table('experiment')
    op.drop_index(op.f('ix_dataset_case_dataset_id'), table_name='dataset_case')
    op.drop_table('dataset_case')
    op.drop_index(op.f('ix_system_version_project_id'), table_name='system_version')
    op.drop_table('system_version')
    op.drop_index(op.f('ix_dataset_project_id'), table_name='dataset')
    op.drop_table('dataset')
    op.drop_table('release_policy')
    op.drop_table('project')
    # ### end Alembic commands ###
